import type { ReceivableSummaryCard, ReceivableTableRow } from '@/components/dashboard/merchant/receivables/types'

export const MERCHANT_RECEIVABLES_SUMMARY: ReceivableSummaryCard[] = [
  {
    id: 'total-value',
    icon: 'money',
    title: 'Total Receivables Value',
    primaryValue: '$340K',
    secondaryValue: '$340,000 USDT',
  },
  {
    id: 'total-funded',
    icon: 'dollar',
    title: 'Total Funded',
    primaryValue: '$300K',
    secondaryValue: '$340,000 USDT',
  },
  {
    id: 'outstanding',
    icon: 'dollar',
    title: 'Outstanding Balance',
    primaryValue: '$120K',
    secondaryValue: 'Owed across receivables',
  },
  {
    id: 'maturity',
    icon: 'money',
    title: 'Upcoming Maturity',
    primaryValue: '$40K',
    secondaryValue: 'Due in 27 Days',
  },
]

export const MERCHANT_RECEIVABLES_ROWS: ReceivableTableRow[] = [
  {
    id: 'r-1',
    receivableName: 'Slippers Bulk Order',
    loanAmount: '$23,000',
    apr: '4.2%',
    repaymentDue: '32 Days',
    repaymentDueVariant: 'upcoming',
    repaymentAmount: '$40,000',
    interestSubline: '$5,000 Interest',
    debtStatus: 'Unpaid',
    debtStatusVariant: 'unpaid',
    rowEmphasis: false,
  },
  {
    id: 'r-2',
    receivableName: 'Slippers Bulk Order',
    loanAmount: '$23,000',
    apr: '6.7%',
    repaymentDue: '-3 Days Ago',
    repaymentDueVariant: 'overdue',
    repaymentAmount: '$40,000',
    interestSubline: '$5,000 Interest',
    debtStatus: 'Defaulted',
    debtStatusVariant: 'defaulted',
    rowEmphasis: true,
  },
  {
    id: 'r-3',
    receivableName: 'Slippers Bulk Order',
    loanAmount: '$23,000',
    apr: '4.2%',
    repaymentDue: 'Repaid',
    repaymentDueVariant: 'repaid',
    repaymentAmount: '$40,000',
    interestSubline: '$5,000 Interest',
    debtStatus: 'Unpaid',
    debtStatusVariant: 'unpaid',
    rowEmphasis: false,
  },
  {
    id: 'r-4',
    receivableName: 'Slippers Bulk Order',
    loanAmount: '$23,000',
    apr: '6.7%',
    repaymentDue: 'Repaid',
    repaymentDueVariant: 'repaid',
    repaymentAmount: '$40,000',
    interestSubline: '$5,000 Interest',
    debtStatus: 'Repaid',
    debtStatusVariant: 'repaid',
    rowEmphasis: true,
  },
  {
    id: 'r-5',
    receivableName: 'Retail Inventory Q1',
    loanAmount: '$18,500',
    apr: '5.1%',
    repaymentDue: '18 Days',
    repaymentDueVariant: 'upcoming',
    repaymentAmount: '$22,000',
    interestSubline: '$2,100 Interest',
    debtStatus: 'Unpaid',
    debtStatusVariant: 'unpaid',
    rowEmphasis: false,
  },
  {
    id: 'r-6',
    receivableName: 'Electronics PO #4412',
    loanAmount: '$31,200',
    apr: '6.7%',
    repaymentDue: 'Repaid',
    repaymentDueVariant: 'repaid',
    repaymentAmount: '$35,400',
    interestSubline: '$3,800 Interest',
    debtStatus: 'Repaid',
    debtStatusVariant: 'repaid',
    rowEmphasis: false,
  },
  {
    id: 'r-7',
    receivableName: 'Garment Wholesale',
    loanAmount: '$12,400',
    apr: '4.2%',
    repaymentDue: '7 Days',
    repaymentDueVariant: 'upcoming',
    repaymentAmount: '$14,000',
    interestSubline: '$800 Interest',
    debtStatus: 'Unpaid',
    debtStatusVariant: 'unpaid',
    rowEmphasis: false,
  },
  {
    id: 'r-8',
    receivableName: 'Office Supplies Chain',
    loanAmount: '$8,900',
    apr: '5.4%',
    repaymentDue: '-1 Days Ago',
    repaymentDueVariant: 'overdue',
    repaymentAmount: '$9,200',
    interestSubline: '$400 Interest',
    debtStatus: 'Defaulted',
    debtStatusVariant: 'defaulted',
    rowEmphasis: true,
  },
]
